export const titles = {
  miner: [{
    title: '排名',
    dataIndex: 'rank',
  }, {
    title: '矿工',
    dataIndex: 'miner_tag',
  }, {
    title: '有效算力/占比',
    dataIndex: 'power_and_proportion',
  }, {
    title: '24H出块奖励',
    dataIndex: 'mining_reward_day',
  }, {
    title: '24H挖矿效率',
    dataIndex: 'mining_efficiency',
  }, {
    title: '24H算力增量',
    dataIndex: 'power_growth_day',
  }],
  minerPower: [{
    title: '排名',
    dataIndex: 'rank',
  }, {
    title: '矿工',
    dataIndex: 'miner',
  }, {
    title: '标签',
    dataIndex: 'miner_tag',
  }, {
    title: '有效算力/占比',
    dataIndex: 'power_and_proportion',
  }, {
    title: '24H出块奖励',
    dataIndex: 'mining_reward_day',
  }, {
    title: '24H挖矿效率',
    dataIndex: 'mining_efficiency',
  }, {
    title: '24H算力增量',
    dataIndex: 'power_growth_day',
  }],
  createBlockApi: [{
    title: '排名',
    dataIndex: 'rank',
  }, {
    title: '矿工',
    dataIndex: 'miner',
  }, {
    title: '标签',
    dataIndex: 'miner_tag',
  }, {
    title: '出块分数',
    dataIndex: 'create_block_number',
  }, {
    title: '幸运值',
    dataIndex: 'luck_value',
  }, {
    title: '出块奖励/占比',
    dataIndex: 'reward_and_proportion',
  }, {
    title: '有效算力',
    dataIndex: 'power',
  }],
  rankankPowerApi: [{
    title: '排名',
    dataIndex: 'rank',
  }, {
    title: '矿工',
    dataIndex: 'miner',
  }, {
    title: '标签',
    dataIndex: 'miner_tag',
  }, {
    title: '算力增速',
    dataIndex: 'daily_power_growth',
  }, {
    title: '算力增量',
    dataIndex: 'power_growt',
  }, {
    title: '有效算力',
    dataIndex: 'power',
  }]
}
